export function HomeDummyText({className}) {
  return (
    <div className={className}>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid a sint, sequi illo, voluptatibus vero accusamus quam voluptas dicta asperiores harum, earum laboriosam accusantium doloremque incidunt culpa natus quibusdam aliquam similique sunt ea distinctio dolor ex? Sit voluptates corrupti explicabo. Accusantium natus sed magnam perferendis. Eveniet ab non repellat consequuntur?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque delectus mollitia accusamus hic, deserunt obcaecati voluptatem ut eum fugit cupiditate nisi dolores aliquam consectetur omnis quia a excepturi iure? Porro, velit recusandae. Reprehenderit aperiam quidem vero. Reiciendis, voluptatem minus. Doloribus assumenda aut facere, eaque aspernatur earum ad, provident consequuntur tenetur quibusdam esse soluta quia asperiores recusandae modi nam iste? Reprehenderit accusamus officia maiores porro dolore ipsam nam illo est labore, fugiat aperiam odio culpa voluptatem, cupiditate nemo non quas quaerat architecto consectetur! Vitae tenetur, voluptas reiciendis ut, alias nam nostrum consectetur voluptates natus ab animi odio quo magni blanditiis in.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque delectus mollitia accusamus hic, deserunt obcaecati voluptatem ut eum fugit cupiditate nisi dolores aliquam consectetur omnis quia a excepturi iure? Porro, velit recusandae. Reprehenderit aperiam quidem vero. Reiciendis, voluptatem minus. Doloribus assumenda aut facere, eaque aspernatur earum ad, provident consequuntur tenetur quibusdam esse soluta quia asperiores recusandae modi nam iste? Reprehenderit accusamus officia maiores porro dolore ipsam nam illo est labore, fugiat aperiam odio culpa voluptatem, cupiditate nemo non quas quaerat architecto consectetur! Vitae tenetur, voluptas reiciendis ut, alias nam nostrum consectetur voluptates natus ab animi odio quo magni blanditiis in.</p>
    </div>
  )
}
